
















function sumEvenFibs(input){
    
    let num1 = 1;
    let num2 = 2;

    let sum = 0;

    while (num2 < input) {
        if (num2 % 2 === 0) sum += num2;
        const tempNum = num2;
        num2 = num1 + num2;
        num1 = tempNum;
    }

    return sum;
}

console.log(sumEvenFibs(4000000))








// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
